//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemontApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public string Appliance { get; set; }
        public int ProblemTypeId { get; set; }
        public string Description { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> StageId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> LastModify { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ProblemType ProblemType { get; set; }
        public virtual StageApplication StageApplication { get; set; }
        public virtual StatusApplication StatusApplication { get; set; }
    }
}
